# Generated by Django 3.0.3 on 2020-04-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='group',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='willgo',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='wontgo',
        ),
    ]
