# Generated by Django 3.0.3 on 2020-04-21 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_meeting_willgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='wontgo',
            field=models.ManyToManyField(related_name='towontgo', to=settings.AUTH_USER_MODEL),
        ),
    ]
