# Generated by Django 3.0.3 on 2020-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
