# Generated by Django 3.0.3 on 2020-05-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200520_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('From', models.TimeField(blank=True, null=True)),
                ('To', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, to='login.Block'),
        ),
    ]
