# Generated by Django 3.0.3 on 2020-05-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('grade', models.IntegerField(default=1)),
                ('years', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('beginning', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='degree',
            field=models.ManyToManyField(blank=True, null=True, to='login.Degree'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ManyToManyField(blank=True, null=True, to='login.Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ManyToManyField(blank=True, null=True, to='login.Degree'),
        ),
    ]
