# Generated by Django 3.0.5 on 2020-05-27 13:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200526_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profile_photos'), upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/student_files'), upload_to=''),
        ),
    ]
