# Generated by Django 3.0.3 on 2020-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200526_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
