# Generated by Django 3.0.3 on 2020-05-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='degree',
        ),
        migrations.AddField(
            model_name='subject',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Degree'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Year'),
        ),
    ]
