# Generated by Django 3.0.5 on 2020-05-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200527_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uploaded_file',
        ),
    ]
