# Generated by Django 3.0.3 on 2020-03-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='quizzes',
            new_name='subjects',
        ),
    ]
