# Generated by Django 3.0.3 on 2020-03-07 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200302_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.IntegerField(max_length=20, unique=True)),
            ],
        ),
    ]
