# Generated by Django 3.0.3 on 2020-03-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
