# Generated by Django 3.0.3 on 2020-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200312_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(null=True, to='login.Subject'),
        ),
    ]
