# Generated by Django 3.0.3 on 2020-03-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200312_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.Subject'),
        ),
    ]
