# Generated by Django 3.0.5 on 2020-04-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_chat', '0004_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_chat.Thread'),
        ),
    ]
